name: sp500sent
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.6.*
  - pytorch-cuda=12.1
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - kagglehub
      - transformers
      - accelerate
      - sentencepiece
